### ISSUE TITLE
Disallow publishing with vanila readme

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-vsce#113]
I would like to do a pre-publish check to ensure that the readme has been customized by the user (and is also not empty).  We could look for a common string in the readme (a watermark of sorts that yo code generated) and if it still exists motivate the user to update it.

If they have not we could forward them to the guidance here:
https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_marketplace-presentation-tips

The goal is to avoid: https://marketplace.visualstudio.com/items?itemName=gerred.theme-plain

cc: @waderyan

**Comment by joaomoreno** [comment]
I'd make it a warning instead of an error.

**Comment by waderyan** [comment]
@joaomoreno are you thinking warning over error because an error would be too invasive? 

Error pros
- Makes it so we don't have stock READMEs in the marketplace (Sean's [example](https://marketplace.visualstudio.com/items?itemName=gerred.theme-plain) above). 
 
Error cons
- If someone really wants to make it a plain README, can we really stop them? Meaning the checks would have to be somewhat complex to keep it from happening. 

Warning pros
- Tells them they need to update the README but doesn't get in there way if they really want to have a plain README

Warning cons
- Someone can still publish a plain README

**Comment by joaomoreno** [comment]
Went with the error and the rule

```es6
/This is the README for your extension /.test(manifestContents)
``

Which seems to be the commonality between [all our templates](https://github.com/Microsoft/vscode-generator-code/tree/master/generators/app/templates).

**Comment by Hyperclaw79** [comment]
Sorry to necro this already implemented feature but, I request a flag to set README check back to a Warning.
**Use Case**:
Local Extensions which aren't targeted for public release need not have to be checked for pre-publish.
And if they do plan on publishing it, users could modify the Readme in a single go before publishing it.
Modifying the Readme just for the sake of creating a `.vsix` for local deployment feels like an unnecessary change imo.

If the proposed flag is implemented, local extensions can be packaged without requiring any Readme changes while the to-be-released extensions can be blocked. It's pretty easy to set this flag as part of VSCode task.

**Alternate Approach**: I'm not sure how exactly the packaging processing takes place but can't the check be made on `vsce publish` instead of `vsce package`?
