### ISSUE TITLE
Bad Request(400) - Value cannot be null. (extensionPackage)

### ISSUE THREAD

**Issue by FFengIll** [Microsoft/vscode-vsce#162]
When I do a publish, a error comes as bellow:
```
Error: Failed Request: Bad Request(400) - Value cannot be null.
Parameter name: extensionPackage
```

This extension has been published successfully some days ago, and I just edit the function code for the new publishing.
Since no details to check, I am puzzled by this case.

**Comment by joaomoreno** [comment]
What version do you have? `vsce --version`

**Comment by FengYouzheng** [comment]
here you are
```
vsce --version
1.20.0
```

**Comment by joaomoreno** [comment]
cc @hamenon @modigrv

**Comment by joaomoreno** [comment]
@FFengIll Does it repro every time? Can you try from another machine? What does `vsce ls` return?

**Comment by amitramesan** [comment]
@FFengIll , did you get a chance to try @joaomoreno 's suggestion of attempting from a different machine?

Would you please share the version details of the vso-node-api package that is being used by vsce on your system ? On a Windows sytem, this would be found inside C:\Users\<<USERNAME>>\appdata\Roaming\npm\node_modules\vsce\node_modules\vso-node-api\package.json : there would be a version entry as below : 
  "version": "6.1.2-preview"

Would you please share this info? Please also share the output of "npm info vsce"

From the error, it seems the vsce on your system is still using the older version of the lib (5.x.x ), ,  even vsce itself is the latest version, 1.20.0 ; if it turns out the lib version being used is older (5.x.x ), would you please try to force upgrade : 

npm install -g vsce -f

If, however, the lib version being used looks good (6.1.2-preview), would you please share a Network trace using Fiddler to help debug further?

**Comment by FFengIll** [comment]
@joaomoreno 
Actually, it does not work in another machine, since all of our machine work with same env.
But I found the reason with @amitramesan 's suggestion: vso-node-api version is 5.x.x with vsce 1.20.

After the upgrade, it works now.
Thx.

**Comment by amitramesan** [comment]
Awesome :-) 

@FFengIll Would you please also share for investigation some information about your environment ; 
1. What OS/Version and SKU/Distribution?
2. What is the NodeJs version?

Thanks,
Amit.

**Comment by FFengIll** [comment]
Env. information as bellow:

Window 10 x64 Home version 14393 
nodejs 6.10.1

**normal with** 

- vsce 1.20
- vso-node-api 5.x.x
- **vscode 1.10.2**

**abnormal with** 

- vsce 1.20
- **vso-node-api 5.x.x**
- **vscode 1.11**

**normal (recovered) with** 

- vsce 1.20
- **vso-node-api 6.1.2-preview**
- vscode 1.11 (and 1.11.1) 

Pls feel free to let me know if any others are required.

**Comment by amitramesan** [comment]
Thank you, @FFengIll  ; this really helps. We'll reach out if we need more info.
