### ISSUE TITLE
Support for scoped naming, e.g., @myscope/package-name?

### ISSUE THREAD

**Issue by vazexqi** [Microsoft/vscode-vsce#186]
I have an VS Code extension that I would like to scope to my org. In usual NPM, I would set `name: @myscope/package-name` in package.json.

However, when I use that with vsce, it says

```
vsce package
Error: Invalid extension name '@myscope/package-name
```

I think this is because of the regex check at https://github.com/Microsoft/vscode-vsce/blob/master/src/validation.ts#L3

Are there plans to support scoped names for extensions?

**Comment by joaomoreno** [comment]
There is no upcoming support for scopes. We don't store extensions in NPM, but in the VS Marketplace.

**Comment by drochgenius** [comment]
I find it a bit confusing the vscode extensions use the `package.json` as their manifest, since this is the NPM package manifest file.

If vscode extensions are meant to be published only to the vscode markeplace, they could have their own manifest for publishing to that marketplace, with a different name, e.g. `vscode-manifest.json`.

This way it would not conflict with `package.json` conventions.

**Comment by eightHundreds** [comment]
[vscode-private-extension-manager](https://github.com/joelspadin-garmin/vscode-private-extension-manager/tree/master/extension) suport store extensions in NPM

**Comment by madcapnmckay** [comment]
+1 for scoped extension packages. 

If trying to use a private extension registry scoped naming is preferable.

**Comment by strazto** [comment]
Workaround for [vscode-private-extension-manager](https://github.com/joelspadin-garmin/vscode-private-extension-manager):

https://github.com/joelspadin-garmin/vscode-private-extension-manager/issues/16#issuecomment-1324500525

**Comment by benduran** [comment]
Hey folks, I know this ticket is eons old at this point, but I wanted to reopen the discussion around allowing a valid `package.json#name` scope. 

Context: My company has been ramping up an internal extension marketplace, and we need to ensure our engineers don't accidentally publish their extensions to the public marketplace, as they're only intended for internal, company-specific consumption.

As a result, we've gain permissions to a number of Netflix-specific NPM scopes, just in case somebody does, _accidentally_, publish something to the public marketplace (NPM, in, particular). We use an internal NPM registry as our publishing location, hence the desire to allow for `package.json` scopes.

How might we best renew the discussion about this? Without an official solution from Microsoft, we're likely to start hacking around the VSCode and `vcse` APIs to try and accomplish what we need.

**Comment by strazto** [comment]
@benduran i'm not fully clear on what you're asking but check out https://github.com/joelspadin-garmin/vscode-private-extension-manager/issues/16#issuecomment-1324500525

**Comment by benduran** [comment]
Thanks for sharing that extension! It came up during my research phase last
year, but it didn’t fully serve the needs we have here. We’ve created our
own, internal, “extension-of-extensions” that taps into our internal NPM
registry, and provides a number of additional IDE enrichment features.

Ultimately, having the vsce CLI support a @my-scope/ package prefix would
be a convenience when compiling the extension. Otherwise, I’ve found a
workaround that performs okay, which involves dropping the scope when using
vsce, then re-adding it before we publish to our internal NPM registry.

- Benjamin
