### ISSUE TITLE
Relative sources in <img> tags in README.md are not rewritten to absolute URLs

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode-vsce#192]
I wrote a readme file in markdown, and I had no problems putting a local gif in it, but vsce complained about a local png, maybe because I inserted it like this (just for centering it):

```md
<p align="center">
	<img src="resources/logo.png" alt="Logo">
</p>
```

**Comment by joaomoreno** [comment]
Can you show me what "complained" means? Did you get an error?

**Comment by fabiospampinato** [comment]
Exactly, more specifically this error:
```
Error: Images in README.md must come from an HTTPS source: resources/logo.png
```

**Comment by joaomoreno** [comment]
Is your extension in a GitHub repository?

**Comment by fabiospampinato** [comment]
Sure, [here](https://github.com/fabiospampinato/vscode-projects-plus) it is.

**Comment by joaomoreno** [comment]
I've cloned that repo and ran `npm i` and then `vsce package`. It worked:

```
vscode-projects-plus master* → vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-projects-plus@1.0.1 vscode:prepublish /Users/joao/Desktop/vscode-projects-plus
> tsc -p ./

Created: /Users/joao/Desktop/vscode-projects-plus/vscode-projects-plus-1.0.1.vsix
```

Something must be off in your machine.

Do you have the latest vsce installed?

**Comment by fabiospampinato** [comment]
You forgot to edit the readme, it worked because now it's written in other way, otherwise I wouldn't be able to publish it because of the error I'm reporting.

Replace this:
```md
<img src="https://raw.githubusercontent.com/fabiospampinato/vscode-projects-plus/master/resources/logo-128x128.png" alt="Logo">
```

With this:
```md
<img src="resources/logo.png" alt="Logo">
```

If you have `sed` available just run:
```
sed -i -e 's/https:\/\/raw.githubusercontent.com\/fabiospampinato\/vscode-projects-plus\/master\/resources\/logo-128x128.png/resources\/logo.png/g' README.md
```

Yes, I'm using the latest version of vsce.

**Comment by fabiospampinato** [comment]
I believe I found the problem, [here](https://github.com/Microsoft/vscode-vsce/blob/6d3a1e43d712b7f15658039517a4b297b144f530/src/package.ts#L325) it checks if the url is relative, but just for images written in the markdown syntax.

If the image is written as an html tab it [doesn't](https://github.com/Microsoft/vscode-vsce/blob/6d3a1e43d712b7f15658039517a4b297b144f530/src/package.ts#L358) run the same check.

**Comment by joaomoreno** [comment]
Got it. We don't support relative paths in `<img>` tags. You simply won't be able to reference that image in that relative fashion and keep using `<img>` tags.

Either keep using a full URL in the `<img>` tag, or drop the centered paragraph tag and use the markdown syntax for images: `![Logo](resources/logo-128x128.png)`

**Comment by fabiospampinato** [comment]
Is there a good reason for not enforcing the same rules for both cases?

**Comment by joaomoreno** [comment]
We try to locate (regex) where images are used in Markdown and upon finding those locations we rewrite their relative URLs to be absolute ones, if we also detect the repository in which the extension will be hosted. We don't do the same for image tags since that is just harder to parse and rewrite. If you feel that passionate about it, feel free to submit a PR which addresses that. 👍

**Comment by letmaik** [comment]
I would find this very useful as well. I can't use the markdown syntax for images as I need to include the `width` attribute. The reason is simple: the image is a screenshot made on a high-dpi screen, and it just blows up in size as browsers don't read pixel density information (which PNGs don't have anyway)  and just assume 72. Setting an explicit width fixes that on all display densities.

Demonstration:

Markdown syntax:
`![](https://raw.githubusercontent.com/letmaik/vscode-git-tree-compare/master/screenshots/main.png)`
![](https://raw.githubusercontent.com/letmaik/vscode-git-tree-compare/master/screenshots/main.png)

HTML:
`<img src="https://raw.githubusercontent.com/letmaik/vscode-git-tree-compare/master/screenshots/main.png" width="230">`
<img src="https://raw.githubusercontent.com/letmaik/vscode-git-tree-compare/master/screenshots/main.png" width="230">

**Comment by chrisdothtml** [comment]
+1

My use case is with aligning images. AFAICT there's no way to do it with markdown

**Comment by Abbyyan** [comment]
But why even if i use  a http url , it can't works. 
`![commands.gif](http://xxxxxx)`
The Error is `Images in README.md must come from an HTTPS source: http://xx`

**Comment by letmaik** [comment]
Switch to https ;-)
