### ISSUE TITLE
Error: Invalid Resource when trying to publish

### ISSUE THREAD

**Issue by brandoncc** [Microsoft/vscode-vsce#196]
This is the first time I have had any issues publishing:

```
(master) λ vsce publish                                                                                                                                                                          (vscode-seeing-is-believing) 12:54:41
Publishing brandoncc.vscode-seeing-is-believing@0.0.4...
Error: Invalid Resource

(master) λ vsce --version                                                                                                                                                                        (vscode-seeing-is-believing) 12:54:56
1.29.0
```

**Comment by joaomoreno** [comment]
cc @modigrv

**Comment by modigrv** [comment]
@joaomoreno I checked there has been no call to Marketplace via Vsce tool for the publisher identity of the vscode-seeing-is-believing extension . Can you please check that whether this error is from vsce tool itself?

**Comment by joaomoreno** [comment]
`Invalid Resource` doesn't seem to be an error which comes from the tool itself. Here's what happens after `Publishing brandoncc.vscode-seeing-is-believing@0.0.4...`:

https://github.com/Microsoft/vscode-vsce/blob/master/src/publish.ts#L59

**Comment by modigrv** [comment]
@brandoncc  This error is being thrown because the PAT used for publishing is no longer valid. 
You can create a new PAT to authenticate the publish - https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate#create-personal-access-tokens-to-authenticate-access
You can pass PAT as a parameter in the publishing step via a -p or -pat option in the vsce tool.

**Comment by brandoncc** [comment]
Thank you both for taking the time to help me. I totally forgot my PAT would expire!

**Comment by joaomoreno** [comment]
@modigrv Could we get a better error message from the service?
