### ISSUE TITLE
Migration Repo

### ISSUE THREAD

**Issue by siamak** [Microsoft/vscode-vsce#202]
I published a extension on vsce. Now we have an organization and we want to migrate repo to org-repo. In vsce how we can do that?

**Comment by joaomoreno** [comment]
Not really sure what our story is there.

cc @seanmcbreen @egamma @dbaeumer

**Comment by seanmcbreen** [comment]
Hi,

we suggest following a process similar to what I have described here:
https://github.com/Microsoft/vscode/issues/21478#issuecomment-283118349

I'll close this issue for now - but please reach out if you have additional questions.

Sean

**Comment by lhl2617** [comment]
Hi -- I'm getting this error (TF14045) when trying to add another user

![image](https://user-images.githubusercontent.com/33488131/120938695-0e658000-c70c-11eb-8866-4b514edb25ca.png)

FWIW, I'm currently developing extension under a university org account, and will be leaving the university and would like it transferred. It seems like adding a personal account is the easier option (other than explicitly deprecating the extension and starting from a clean slate). I suspect that people outside the org cannot be reached and hence the error.

I was able to add another user in the same org (university).

It's been four years since extension transferral was requested--any updates on a better flow?
