### ISSUE TITLE
Extension package is malformed/corrupted

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-vsce#211]
@shanalikhan says

I'm trying to publish the extension but getting this error.
Npm install works build 
Build works fine.

Is there any logs from which i can see where the issue is ?

```
PS C:\Dropbox\Github_Repo\code_extension\code-settings-sync> node --version
v8.9.0
PS C:\Dropbox\Github_Repo\code_extension\code-settings-sync> npm --version
5.5.1
PS C:\Dropbox\Github_Repo\code_extension\code-settings-sync> npm install

> code-settings-sync@2.8.5 postinstall C:\Dropbox\Github_Repo\code_extension\code-settings-sync
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.15.0
Found minimal version that qualifies engine range: 1.15.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/vscode
.d.ts
vscode.d.ts successfully installed!

npm WARN code-settings-sync@2.8.5 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current:
 {"os":"win32","arch":"x64"})

added 115 packages in 11.344s
PS C:\Dropbox\Github_Repo\code_extension\code-settings-sync> vsce publish
Executing prepublish script 'npm run vscode:prepublish'...

> code-settings-sync@2.8.5 vscode:prepublish C:\Dropbox\Github_Repo\code_extension\code-settings-sync
> tsc -p ./

Publishing Shan.code-settings-sync@2.8.5...
Error: Extension package is malformed/corrupted
```

**Comment by joaomoreno** [comment]
@shanalikhan says

I had to clone the repo and did npm install again and it was fixed.
But there should be a way to get what caused it corrupted

**Comment by joaomoreno** [comment]
@modigrv Any way I can get the reason for the malformation/corruption back from the response?

**Comment by modigrv** [comment]
We throw this error when we get a File format exception. This is raised when the vsix file could not be opened at all. So detailed information is not available as the zip utility is not even able to open the file.

**Comment by cancerberoSgx** [comment]
i'm blocked with this one. DO you know how I can reproduce the error locally so I have a clue ? is the error in package.json or could it be anywhere?  Tried a lot of changes and rolling back - i'm kind of giving up.  didn't found any way of debugging or obtaining some clue if what's wrong - just that message..... seems to be a remote validation... . any tip is most appreciated. thanks in advanced.

**Comment by cancerberoSgx** [comment]
Update: I rollback all I could , login again with a new token , increase version, downgrade nodejs/npm, use yarn, reset to the original json file indentation, detect hidden characters, and no luck. Could it be that's something special in my project or in the server ? should I create another published id  and other repo / extension id ? 

Also I'm observing that when executing vsce package the vsix file its generated OK and I'm able to open it with several technologies. But it has the entire node_modules folder inside  I don't know if that's OK, it doesn't sound like it is, I tried to add node_modules/** to .vscodeignore but it still adding it. Is that's the expected behavior ? (users will download 100mb file when installing it ? )

thanks any tip is most appreciated

**Comment by evgenyk** [comment]
Having the issue publishing extension on Ubuntu (18.10), while exactly with the same code, when checked-out on Windows succeeds publishing.

More error logging would help for sure, so we don't look for a black cat in a dark room.

```
Publishing evgenyko.pogo@1.3.6...               
ERROR  Extension package is malformed/corrupted
```

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

**Comment by bmewburn** [comment]
I'm getting this error too with 1.64.0. Is there any way to output more info on the cause?

```
Publishing bmewburn.vscode-intelephense-client@1.1.1...
 ERROR  Extension package is malformed/corrupted
```

**Comment by bmewburn** [comment]
Running vsix file through `unzip -t` doesn't show any problems with the file. Also tried fixing with `zip -F` which yielded another valid file that also failed with malformed/corrupted error using `vsce publish --packagePath`.

**Comment by kesane-msft** [comment]
@bmewburn , did/could you try [publishing via the web UI](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#upload-your-extension) (use the Visual Studio Code option) from your Linux box? This would help us investigate the issue in more detail.

**Comment by bmewburn** [comment]
@kesane-msft , yes I tried `vsce package` on linux then uploading via the web UI (linux/firefox) but it failed with the same error message. Some other things I tried unsuccessfully included trying with the previous 10 versions of vsce then cloning vsce, upgrading the yazl package, building.

**Comment by kesane-msft** [comment]
Thanks for the details @bmewburn . When you successfully uploaded the extension from the windows machine, did you use the same package that was built on your Linux box or did you repackage the extension and publish it?

**Comment by bmewburn** [comment]
No, I didnt try publishing the linux package from windows. I git cloned, npm install, vsce publish on a windows 10 machine.

**Comment by bmewburn** [comment]
I found the problem in my case. It was linux having a case sensitive file system while windows has a case insensitive fs. In my linux package I had 2 files with the same case-insensitive path.

**Comment by juliosaenz** [comment]
I am also facing this problem. i am trying to upload via the Web UI and i get this error.
Can you please add more logging here, this is frustrating i don't know what to fix.
i am using a windows machine to build the vsix

**Comment by cancerberoSgx** [comment]
juliosaenz 

> I am also facing this problem. i am trying to upload via the Web UI and i get this error.
> Can you please add more logging here, this is frustrating i don't know what to fi


you should provide  the package or with the problem  so devs cab reproduce the problem
I assume you are in windows and checked vscode and your projecy's dependencies are updated / latest 


Did you tried: clean up node_modules package-lock.json,Verify that your package.json dependencies are correct and don't point to local dependencies. At last update all dependencies to latest , clean up a, test and try again. 
It was a pain for me too when dealing with extehsions - the painful part  for sure.. I leab that having control of dependencies is important ,,,, don't go too crazy  with npm install and verify onfen that the publish command still works in between... :(  Last rert, try rollbacking all the changes to a working versoin ann try to publish that from scratch / empty folder. could help isolate the problem..

**Comment by juliosaenz** [comment]
adding the file here as a zip, since GitHub does not allow me to paste a vsix.

[XapDeveloperExperience.XapInfo-0.1.0.zip](https://github.com/microsoft/vscode-vsce/files/3474773/XapDeveloperExperience.XapInfo-0.1.0.zip)

I don't have any dependencies per say. 
I will try to clean the node_modules folder and start from scratch.

**Comment by juliosaenz** [comment]
any ideas or possibility of adding more logs. I tried the suggested fixes with no luck

**Comment by kesane-msft** [comment]
@juliosaenz, I am from the Marketplace team. 
First of all, sorry for the problems that you are facing.

I took a look at your extension and it seems that there is a duplicate x128.png file in the Images folder, that is causing the issue. Try removing that and you should be able to proceed.

Regarding adding more logging, basically the error is thrown when the package cannot be extracted at all and hence we don't have much details of what the error was. The library used for the extraction too doesn't give much details.
That said, maybe we can add an error message hint about checking for duplicate files, since that seems to be the most common reason for this error. That might reduce some frustration. 😄 

One last thing - I noticed that your extension has SVG assets. We block SVG assets in extensions - you can find more details [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions). So unless you remove that you would hit extension validation errors.

**Comment by evgenyk** [comment]
Hello @joaomoreno, thank you for sharing more light into the internals of the tooling you are using and its limitations.

On the other hand, it feels like you are getting paid for closed tickets.

I am not convinced that technically doing nothing when multiple people have the same problem qualifies as a closed issue.

**Comment by juliosaenz** [comment]
Thanks @kesane-msft I did not realize the zip had two images with the same name. it is weird why the packaging tool would put two of them in there. Because on disk there is only one. I wonder if it is because it is referenced in the vss-extension.json like this

…  
"icons":
{
      "default": "images/x128.png"
},  
{
      "path": "Images",
      "addressable": true,
      "packagePath": "Images"
},
…

But I will definitely remove the svg if it is not supported. one quick petition from my side to make it easier for us to fix errors. as others in this thread I was able to unzip the extension with no problem so the error is not the format of the zip. I know you are not using straight ZIP to unpack. But would it be possible for you process to IIF the package fails to unpack with you tool, to then unpack it with ZIP and do a sanity check? this sanity check information would be very useful and self-serving for all your customers. as an example this double image in the ZIP can be found, and the inclusion of svg images can also be found

**Comment by joaomoreno** [comment]
@evgenyk Every single user who had this issue had files with the same name but different casing in their extension folder.

I just cloned https://github.com/pogo-stack/pogo_vscode.git and was able to successfully package and publish this under my publisher, on Ubuntu. Which means something else is wrong. Can you still reproduce this if you clone the repo into another folder and try publishing it from there?

**Comment by evgenyk** [comment]
The extension is publishing ok now, thank you.

The problem was with casing treatment between package and the file-system, as we have mixed-OS developers. That took way more time to find it out than is reasonable, and this is on a small extension.

My point was not that it is not possible to find-out what is wrong with trial and error (different systems behave differently without apparent debugging mechanism), but that extending messaging from the server is desirable in this case. 

Or rather additional validation inside the `vsce` tool added, so that we could be sure that the packaged extension is indeed valid and ready to be submitted.

**Comment by joaomoreno** [comment]
@evgenyk You're absolutely right.

@kesane-msft Given the lack of server side reporting, I'm forced to validate case insensitive duplicates on the client side, so pushing a validation rule for this.

**Comment by alansferreira** [comment]
Hi, i received this same generic message, on my case, the **microsoft** has increase marketplace rules to require **minimum icon size to 128x128** and **square**, but the **tfx CLI** not follow original error and outputs an generic message.
