### ISSUE TITLE
vsce not working with travis CI

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode-vsce#237]
Hello, 
I am building the settings sync extension in my computer and it works well.
I have recently added Travis CI and it fails 

![image](https://user-images.githubusercontent.com/8774556/35941530-5a52c424-0c74-11e8-9547-f405dd83234f.png)

https://travis-ci.org/shanalikhan/code-settings-sync/jobs/338701293

**Comment by joaomoreno** [comment]
This isn't vsce, but the `vscode` node module. Filed https://github.com/Microsoft/vscode-extension-vscode/issues/91

I recommend you pick a more recent NodeJS version in Travis: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions

**Comment by TomasHubelbauer** [comment]
This issue is pretty high up on Google for VS Code extension with Travis queries so I'd like to link [Running tests automatically on Travis CI build machines](https://code.visualstudio.com/Docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines) here which has a working Travis configurating for running VS Code extensions tests.
