### ISSUE TITLE
`vsce publish` fails with "Error: The category 'Languages' is not available in language 'en-us'."

### ISSUE THREAD

**Issue by jrrdnx** [Microsoft/vscode-vsce#253]
Used `vsce publish` a week ago with no issues. Yesterday and today, I've tried to push up a new version but it always fails with an error:

> Error: The category 'Languages' is not available in language 'en-us'.

The only change I made to **package.json** was to update my version from **0.1.0** to **0.1.1**. The categories field is currently set to:

```json
"categories": [
    "Languages"
],
```

Using vsce **1.37.6**

**Comment by DonaldHays** [comment]
I am experiencing the exact same issue. I was able to publish a day or two ago, but haven't been able to this morning with that exact error.

I get the same error both using `vsce publish` and the web-based VSIX upload.

**Comment by monkeygroover** [comment]
Same for me

**Comment by Tehnix** [comment]
Currently blocked on publishing because of this, at https://github.com/alanz/vscode-hie-server/blob/master/package.json#L26.

**Comment by monkeygroover** [comment]
Appears to be working again, must have been a server side issue.

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

**Comment by pkuma-msft** [comment]
Yes, this was an issue on Marketplace's side. We disabled the feature flag for mitigation. We are working on a fix..

**Comment by mike-lischke** [comment]
Fails for me too currently 😡

**Comment by viradhamMS** [comment]
@jrrdnx , @mike-lischke : Meanwhile, if you can use the category "Programming Languages", it will unblock your publish. Can you please try this?

**Comment by viradhamMS** [comment]
BTW, the issue is fixed now. you can use either of the categories. I suggest to use the new one going forward - "Programming Languages"

**Comment by mike-lischke** [comment]
The problem with that is that my extension now fails to activate.

**Comment by shaaradmsft** [comment]
Hi @mike-lischke could you please elaborate on the failure you're seeing? We tried forking your repository, changing category to `Programming Languages`, building the extension with `vsce` and installing it on VSCode. The syntax highlighting and error checking worked for antlr files.

**Comment by mike-lischke** [comment]
Is it possible for you to install the 2.0.1 release of my extension from the marketplace? Meanwhile I updated that to make it work again.

What I saw was that after updating the extension in vscode I got a message for my .g4 files saying that there are extension in the marketplace that could handle such files. And no of the extension features worked. Most obviously the syntax highlighting was different, also symbol lookup didn't show anything. This told me enough, since the only change I made was that language setting. So I reverted that and published an update, to avoid frustration for my users.

**Comment by shaaradmsft** [comment]
Hi @mike-lischke , we checked the 2.0.1 release of your extension and that has category `Languages` and not `Programming Languages` (categories are same in 2.0.1 and 2.0.2). Also, the verison 2.0.1 isn't giving syntax highlighting as you said. Would it be possible due to the other changes/updates present in version 2.0.1? Could you please mail us at VSMarketplace@microsoft.com and we'll share with you the 2.0.1 release.
