### ISSUE TITLE
Option to use a particular .vscodeignore file

### ISSUE THREAD

**Issue by akshita31** [microsoft/vscode-vsce#255]
Is there an option to use a particular .vscodeignore file (which may not be present directly in the current working directory or one with a different name) ?

**Comment by TheRealPiotrP** [comment]
The ability to specify .vscodeignore files to vsce would help extensions like C# increase the determinism of their builds. Extensions like ours require access to the internet at runtime to download platform-specific components [in our case this is OmniSharp as well as a .NET Debugger implementation]. It is necessary for us to build two flavors of our VSIX, one that downloads these assets on the fly and another, much larger, that includes platform-specific components. The portable package explicitly needs to ignore the platform specific components used during its own build. The platform specific flavor, conversely, needs to include these components.

We currently achieve this behavior through a combination of implicit build timing as well as a .vscodeignore file that is the lowest common denominator of these two package flavors. This is quite fragile, as you might imagine, and has recently become impossible due to capabilities we want to add to our build.

We are currently going to work around this problem by generating the .vscodeignore file during the packaging process. This solution is sub-optimal for a number of reasons:
  * we need to generate a build artifact into the project's root directory. This replaces one type of complexity with another. Our scenario requires we undertake this tradeoff, but it's far from ideal.
  * The default `vsce package` experience will run with an arbitrary .vscodeignore file, or none if it has yet to be generated. Given the importance of this file to the VSCE experience, it would be great if vsce could produce a warning if it sees multiple .vscodeignore files and one is not specified, perhaps an error even.

**Comment by joaomoreno** [comment]
Sure, we'll take a PR for this. Shouldn't be too hard.

Maybe a `--ignore-file FILE_PATH` option?
