### ISSUE TITLE
Support yarn workspaces

### ISSUE THREAD

**Issue by siegebell** [microsoft/vscode-vsce#300]
Feature request: support [yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/).

`vsce --yarn` (as of 1.52.0) does not package any of the modules from the root's `node_modules/`.

**Comment by kranthie** [comment]
Hi @joaomoreno: any idea if this support will be added soon?

**Comment by yuxuan** [comment]
We have a multiple extensions with some common packages mono-repo structure. Each extension has dependencies on few of those common packages. 

Currently we are using Lerna to manage the mono-repo, using webpack compile packages for each extension, and using vsce package individual extension and publish it. 

It would be great if vsce support this natively

**Comment by bd82** [comment]
I've worked around this by:
- Using `nohoist` to force all (transitive) deps of the VSCode ext to be present in its own `node_modules` directory. 
- Calculating the list of dependencies to be bundled myself.
- Calling `vsce package` **programmatically** and **injecting** the previously computed list of dependencies using `proxyquire`

See here:
- https://github.com/SAP/ui5-language-assistant/blob/master/packages/vscode-ui5-language-assistant/scripts/bundle-vsix.js

**Comment by phaumer** [comment]
Another requirement is that it should support webpack as well as exceptions specified in the .vscodeignore file such as 

```
node_modules/**
../../node_modules/**
!../../node_modules/vscode-jsonrpc/**
!../../node_modules/vscode-languageclient/**
!../../node_modules/vscode-languageserver-protocol/**
!../../node_modules/vscode-languageserver-types/**
!../../node_modules/vscode-nls/**
```

**Comment by bd82** [comment]
Note that if you bundle your extension, e.g using webpack you won't need the contents of the node_modules inside your vsix.

**Comment by rbuckton** [comment]
Is this still an issue? I'm using yarn workspaces and was able to successfully package a `.vsix` using `vsce package --yarn` and it collected the `node_modules` from the root just fine.

- `vsce` 1.79.5
- `yarn` 1.22.4

![image](https://user-images.githubusercontent.com/3902892/94182808-5aaab180-fe56-11ea-8be8-4bcaf3b65964.png)

**Comment by rbuckton** [comment]
Interestingly enough, running `npx vsce@1.52.0 ls --yarn` in the same repo also lists `node_modules` in the root. I also checked the outputs of `npx yarn@1.15.0 list --prod` (as well as some earlier versions back through `yarn@1.4.0`), and they also include the hoisted dependencies. 

It could be that I'm running `vsce` from the root, rather than from within a workspace folder (since I'm planning on bundling the packages anyway in the future).

**Comment by rbuckton** [comment]
You can safely ignore my last two comments. After looking at the PR code in #458 I can see that your goal was to run `vsce publish` from within a specific workspace folder, not the workspace root.

I just put up #480 to auto-detect `--yarn`, but that may need to be modified slightly if your PR goes in so that it also looks for a yarn workspace root (so you could just do `vsce publish` from within the workspace folder rather than `vsce publish --yarn`).

**Comment by thegecko** [comment]
I managed to get `vsce package` working perfectly with `yarn` in a monorepo with the following 3 changes:

- Use [vsce-yarn-patch](https://www.npmjs.com/package/vsce-yarn-patch) instead of `vsce` which (I believe) is a published fork of this repo including #493. Without this, all `node_modules` in the monorepo are included
- Run vsce package with the `--yarn` switch (e.g. `vsce package --yarn`) to ensure the yarn algorithms are used (otherwise `npm` seems to be used)
- Create an empty `yarn.lock` file in the project being packaged. This side-steps the check outlined [here](https://github.com/microsoft/vscode-vsce/blob/396a66f3539f6e913d8e440a3d6a8e950fbeddb5/src/npm.ts#L188) which shouldn't be done in a monorepo

HTH

**Comment by connor4312** [comment]
This has been published in the latest version of `@vscode/vsce`. Is that version working for folks?

**Comment by TylerLeonhardt** [comment]
This is verified. I created the following test:
* download and unzip: [yarn-workspaces.zip](https://github.com/microsoft/vscode-vsce/files/14069938/yarn-workspaces.zip)
* run `yarn` at the root
* `cd ./packages/test-calculator` into the vscode extension
* `npx @vscode/vsce@latest package --yarn`

This folder contains:
* A root package.json that uses `workspaces`
* a folder under packages that is a "node library"
* a folder under packages that is a VS Code extension
