### ISSUE TITLE
Add images to readme without having a repository

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-vsce#390]
Hey,

I am writing a vscode extension that is intended to be used only by my team, so I cannot publish it to the marketplace, or have it in a repo other than our own servers (company policies).

I would like to add an icon to the extension and some pictures and gifs to the Readme but vsce won't package the extension into a vsix if I don't provide a repo link.

Is there a way to get around that?

**Comment by joaomoreno** [comment]
What's the error you're getting?

**Comment by psclkhoury** [comment]
@joaomoreno I have a local gif that I want to add to the readme and I have no repository specified in the `package.json`
```
![extension demo](demo.gif)
```
And this is the error that I get:

 ERROR  Couldn't detect the repository where this extension is published. The image 'demo.gif' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.

**Comment by joaomoreno** [comment]
Have you tried passing `--baseContentUrl` and `--baseImagesUrl`?

```
  --baseContentUrl [url]  Prepend all relative links in README.md with this url.
  --baseImagesUrl [url]   Prepend all relative image links in README.md with this url.
```

**Comment by psclkhoury** [comment]
I tried, but as I said, I dont have URLs to append.

My repo looks like this:

![image](https://user-images.githubusercontent.com/9846892/66630897-61b8bf80-ec05-11e9-86b8-ad0b5c117bb3.png)

I want to use `demo.gif` inside the `README.md` and distribute the `vsix`, without having any repo or urls.

Is that possible or vscode doesnt support showing images in the `README.md` that are not from some url.

**Comment by joaomoreno** [comment]
If you have no URLs to append simply add `--baseContentUrl none` and `--baseImagesUrl none` as a workaround for now.

**Comment by psclkhoury** [comment]
Also tried that, doesn't work. I get this error when running `vsce package --baseContentUrl none --baseImagesUrl none`

 ERROR  Images in README.md must come from an HTTPS source: none/demo.gif

**Comment by joaomoreno** [comment]
Oh, then use `https://none` instead.

**Comment by psclkhoury** [comment]
Now I get a broken image in the README when I install the extension.

This is just a waste of time. I'm gonna close this. Probably vscode only supports images in README coming from a repository.

**Comment by joaomoreno** [comment]
Yeah, VS Code supports images in README coming from a URL only, unfortunately.

**Comment by psclkhoury** [comment]
@joaomoreno I don't know if it is an overload, because visual studio has a mechanism to distribute self hosted extensions via private galleries. That way you always get update notifications even if the extension is not published in the martketplace. 

Unfortunately, vscode doesn't have something similar as far as I can tell, so now it's a big hassle to write private extensions and distribute them.

Hopefully they will add this soon.

Thank you for your help

**Comment by joaomoreno** [comment]
> Unfortunately, vscode doesn't have something similar as far as I can tell, so now it's a big hassle to write private extensions and distribute them.

Is there anything else not working, besides images?

**Comment by psclkhoury** [comment]
Actually there already is a feature request for that [here](https://github.com/microsoft/vscode/issues/21839)



> 
> Is there anything else not working, besides images?

Nope that was the only thing that I was missing for now. Thanks

**Comment by whlkw** [comment]
VS Code still supports images in README coming from a URL only?

**Comment by LucidOcean** [comment]
Wow, you cant put a few images in the vsix package and use in readme?

**Comment by biel-correa** [comment]
Did anyone find a solution to this?

**Comment by Livven** [comment]
@biel-correa You could inline them as base64, but not sure whether there are any practical limits regarding file size here.

**Comment by biel-correa** [comment]
> @biel-correa You could inline them as base64, but not sure whether there are any practical limits regarding file size here.

I solved it, instead of linking an image you can just drag it when you are writing the MD file, github will create a special link for it

**Comment by RovoMe** [comment]
@psclkhoury I don't think that the inability to use local images, either by directly linking to them or embedding those as base64 images within markdown image links, is related to the request to provide private marketplaces. IMO Microsoft just needs to change the way `vsce` "validates" links in README's that either point to an external source or are embedded within the artifact to generate. Currently they produce an error and fail the creation of the artifact when a outputing a warning and continue with the build would be the appropriate thing to do.

Currently I'm working on a private extension that is hosted on our private Gitlab repository located on our own protected servers where you basically need VPN access to access the server at all. Besides that Gitlab requires a login itself, which can be done i.e. through OAuth2. While the README when consumed in a browser after loging in with our Gitlab server is fine with all the images, `vsce` will refuse to generate the VSIX file as it can't resolve the images addressed by local pathes. I can "convince" `vsce` by specifying `--baseContentUrl` and `--baseImagesUrl` flags pointing to our private Gitlab project to generate the VSIX file successfully, however the images don't show up in the details of the extension itself as Gitlab will redirect the request to the login page as no OAuth2 token is available. As such the image links are therefore broken in the extensions details tab anyway.

The issue I'm facing now though is that I use [vscode-extensions-tester](https://github.com/redhat-developer/vscode-extension-tester) to perform some automated UI tests as part of the integration test step phase in our build pipeline. ExTester does internally trigger a VSIX packaging build by executing `vsce --no-yarn` command and [ignoring any other parameters specified](https://github.com/redhat-developer/vscode-extension-tester/issues/441) in the package script defined in the package.json file. The generation of the VSIX file for integration testing therefore fails as it can't resolve the images. Only when I remove all links to images or other doc pages the VSIX file can be generated at all.

While images in the README / details section of the extension are nice-to-have, they are not the main concern of the extension. As such, failing a build due to the inability to resolve those images, even though locally available, at package time isn't smart at all and should be reduced to warning level and continue the package build. While I do support the incentive to add support for private marketplaces, there is [OpenVSX](https://github.com/eclipse/openvsx) which more or less allows to run its own private marketplace where one can publish extensions to. OpenVSX supports upstream marketplaces which can be used to access extensions hosted on that marketplace through your private-run one while your extensions aren't propagated to that marketplace. The only downside to this though is that you basically have to use the free [VSCodium](https://vscodium.com/) deployment rather then VSCode itself.

**Comment by sovetski** [comment]
Any update on it? I dont understant why we can add an image for icon in `package.json`, but not for `readme.md`?

**Comment by JoanComasFdz** [comment]
After running `vsce package` with some fake urls, I unzipped the .vsix file and saw that the path to the images was rewritten.

So I fixed the paths and zipped again and renamed. Then i install it again and... the images are still broken.

I understand you don't want people uploading extensions with 100mb videos in them, but its surprising that VS Code cannot resolve an image that is zipped together with the extension, when it can show the icon.

**Comment by tomqwpl** [comment]
I was surprised by this too. I have a similar situation where the source code for the extension is in a private repo, but we're publishing the extension in the normal marketplace. So I'm going to have to work round this by artificially adding the images to a public github repo so that they can be displayed.

Given that the URLs that are generated are just things like "https://github.com/blah/blah/raw/HEAD/images/blah.gif" presumably there is also a versioning issue. 
If I change my extension such that I invalidate the images and want to recreate them, I need to make sure I use a different image name, otherwise the image will change for prior versions of the extension too. This could presumably lead to people seeing images related to versions of the extension they don't actually have. Once an image is created it should never be modified, or indeed never deleted, as otherwise it will affect users that don't instantly update to the latest extension release the moment it is released?

**Comment by laizp** [comment]
Any updates about this?

**Comment by arnoudbuzing** [comment]
Just want to throw my hat into this ring. We have spent a lot of (wasted) time trying to get this to work. It seems that if you include images (screenshots are common) in the extension documentation, then you should be able to link to them from the README.md file (or any markdown file, really). Please consider raising the priority on fixing this issue. Thanks.

**Comment by laizp** [comment]
I find that vsce supports the `--no-rewrite-relative-links` option for adding images with relative paths to README.md

https://github.com/microsoft/vscode-vsce/blob/33daacd8595c663db531252bb2ba624111426012/src/main.ts#L105

But although images are packed into the .vsix file, these images don't show on the vscode extension page because vscode will sanitize the markdown content before rendering them (see [here](https://github.com/microsoft/vscode/blob/e47ec0a8791a6a79736bb14e29d6c0c7504b66bb/src/vs/workbench/contrib/markdown/browser/markdownDocumentRenderer.ts#L232)). Unfortunately the code indicates that it only supports 3 kinds of [protocols](https://github.com/microsoft/vscode/blob/e47ec0a8791a6a79736bb14e29d6c0c7504b66bb/src/vs/workbench/contrib/markdown/browser/markdownDocumentRenderer.ts#L159), not including the images of relative path.

But then again, the [`hookDomPurifyHrefAndSrcSanitizer()`](https://github.com/microsoft/vscode/blob/e47ec0a8791a6a79736bb14e29d6c0c7504b66bb/src/vs/base/browser/dom.ts#L1826) function supports the `allowDataImages` option in the second arg, and the [`sanitize()`](https://github.com/microsoft/vscode/blob/e47ec0a8791a6a79736bb14e29d6c0c7504b66bb/src/vs/workbench/contrib/markdown/browser/markdownDocumentRenderer.ts#L162) function sets it to true, indicates that **maybe** we can make it rendering a base64 image. So, we could make vsce support base64 images or only transpile the original README.md when package it (so we can still use the relative path in README.md). If someone can make a PR.

**Comment by fathulfahmy** [comment]
Workaround I've implemented for this issue is to use both `<img src="docs/example-image.png">` and `![](docs/example-image.png)`. Strange behavior is that some images are valid with `<img>`  and some are valid with `![]()` and by validity I mean passing the test when running the `vsce publish` command.
