### ISSUE TITLE
Can't publish extension (ERROR  read ECONNRESET)

### ISSUE THREAD

**Issue by knopp** [microsoft/vscode-vsce#446]
Lately I'm having issues publishing extension. It's been going on for few days. Yesterday I managed to get it published after maybe 20 tries.

It times out after a while with
`ERROR  read ECONNRESET`

VSCE 1.75.0
Node v14.0.0

**Comment by joaomoreno** [comment]
Are you behind a proxy? Can you reproduce in another machine? In the same machine but a different network, in case it's a laptop?

**Comment by knopp** [comment]
No proxy. I also tried with VPN from different locations so it shouldn’t be a routing problem. Weird thing is that it works occasionally (maybe one in 20 tries).

**Comment by s0kil** [comment]
I'm having the same problem `ERROR read ECONNRESET`

**Comment by s0kil** [comment]
I have tried downgrading to Node.js version `13.14.0` from `14.2.0` and was able to publish the extension.

**Comment by joaomoreno** [comment]
@knopp Can you check @s0kil's workaround, whether that fixes it for you as well?

**Comment by wapenshaw** [comment]
I'm having the same issue today! I am on node v14.2.0 and was able to publish yesterday! same theme extension and some changes, I can't publish today, above that I think the versions are messed up as well. 

I am not behind any proxy, same env as last publish.

**Comment by joaomoreno** [comment]
@knopp @musm Does downgrading Node work for you?

**Comment by knopp** [comment]
I wasn't able to reproduce this recently. Seems intermittent.

**Comment by musm** [comment]
Oddly I also now can't reproduce it.

**Comment by joaomoreno** [comment]
👍 Let me know if it comes back.

**Comment by kahole** [comment]
I've been having this issue past 24 hours. Not being able to publish a new version of the extension.
```
❯ node -v
v14.7.0
❯ vsce -V
1.78.0
```

```
Publishing kahole.magit@0.4.1...
 ERROR  read ECONNRESET
```

**Comment by orhun** [comment]
Same issue here. `sudo n 13.14.0` worked for me.

**Comment by caasi-dev** [comment]
Had the same issue on Arch Linux, downgrading from 14.9.0-1 to 12.18.3-1 (LTS nodejs-lts-erbium) solved the problem.

**Comment by comalice** [comment]
Also having this issue on Arch Linux:
```
$ node -v
v14.12.0
$ vsce -V
1.80.0
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-teraterm-lang@0.1.0 vscode:prepublish [snip]/vscode-teraterm-lang-2
> npm run compile


> vscode-teraterm-lang@0.1.0 compile [snip]/vscode-teraterm-lang-2
> tsc -p ./

 DONE  Packaged: [snip]/teraterm-lang-2/vscode-teraterm-lang-0.1.0.vsix (16 files, 26.49KB)
$ vsce publish
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-teraterm-lang@0.1.0 vscode:prepublish [snip]/vscode-teraterm-lang-2
> npm run compile


> vscode-teraterm-lang@0.1.0 compile [snip]/vscode-teraterm-lang-2
> tsc -p ./

Publishing AlbertLatham.vscode-teraterm-lang@0.1.0...
 ERROR  read ECONNRESET
```
As @caasi-dev says, downgrading to 12.18.3-1 (LTS nodejs-lts-erbium) fixes the problem.

**Comment by WLyKan** [comment]
I encounter this problem whit `node 14.9`.
I fixed this with `nvm use 12.18.4`

**Comment by AurelienRibon** [comment]
For the record, I also encountered the same issue today with the LTS version of node 14. I was able to publish multiple extensions during the previous weeks (and yesterday) with the same version. And today, ECONNRESET all the way...
Moving to node 15 solved the issue, but left a strange taste in the mouth :) Good luck on finding the root cause, it seems a nasty issue.

**Comment by SimchaYork** [comment]
I am encountering this issue on two separate machines. Each running vsce 1.81.1 and node 14.15.0. When I use 'vsce publish', it spends a bit of time trying to publish before returning 'ERROR read ECONNRESET'.

I upgraded to node 15.2.0 on one machine and it then worked fine.

**Comment by oliversalzburg** [comment]
So I've also run into this and can't publish since yesterday. To me, this smelled like a backend issue.

I captured the network traffic with Wireshark and inspected which Marketplace node I'm being connected to. For me that is `13.107.42.18`.

When you visit http://13.107.42.18/, you see the following message in your browser:
> <h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>05RTbXwAAAADeo6k/4aTxQ6pnjsFE44RwRFVTMzBFREdFMDQwOABFZGdl

I can work around the issue by `vsce package`ing my extension and then manually uploading the package at `https://marketplace.visualstudio.com/manage/publishers/<publisher name>`.

I hope this helps someone. If someone at Microsoft can be nudged to restore the API services, that'd be nice though :)

**Comment by ArturoDent** [comment]
Been working fine for weeks.  Wouldn't work for last two days.  Upgraded to node v15.9.0 and it worked instantly.

**Comment by Noxdor** [comment]
I had the same issue with Node v14.15.2. Followed @ArturoDent's suggestion and updated to v15.12.0, it then worked just fine. I recommend only adding node v15 in the extension folder instead of updating it globally, to keep working with the LTS.
Just go into the folder/repository of the extension you want to publish with `vsce`, run `npm install node` without the `-g` flag and then run your `vsce publish`.

**Comment by marlongerson** [comment]
> Been working fine for weeks. Wouldn't work for last two days. Upgraded to node v15.9.0 and it worked instantly.

Thanks. I upgraded to v16.4 and it worked.

**Comment by phil294** [comment]
error persists on latest Manjaro(Arch) Linux, node 16.16, vsce 2.11.0.
