### ISSUE TITLE
Automatically enable `--yarn` if `yarn.lock` is found

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-vsce#480]
How about that guys?

**Comment by rbuckton** [comment]
It could also detect the presence of a `.yarnrc` file.

Or, as an alternative, support adding a way to add project-local configuration that `vsce` could pick up and would allow you to specify defaults for `--yarn` (as well as `--baseContentUrl`, `--baseImagesUrl`, and a few others). Something like one of the following:

- An entry in `package.json` (since that's used for other settings related to the extension)
- A `.vscerc` or other configuration file.

**Comment by felipecrs** [comment]
Yes, that would be very useful, but I believe it deserves its own Issue. To do that, I strongly recommend [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig). :-)

**Comment by rbuckton** [comment]
I created a PR for this since I'd also find it useful.

**Comment by rbuckton** [comment]
Another detection method might be the presence of a `"workspaces"` key in `package.json`, since that is generally indicative of a project using yarn workspaces.

**Comment by felipecrs** [comment]
> Another detection method might be the presence of a `"workspaces"` key in `package.json`, since that is generally indicative of a project using yarn workspaces.

It seems that npm v7+ is going to support Yarn `workspaces`, so I think it's not a good idea to use as detection criteria.

**Comment by felipecrs** [comment]
@joaomoreno are planning to release this anytime soon?
