### ISSUE TITLE
Question: Include OS specific binaries in an VSCode extension?

### ISSUE THREAD

**Issue by megel** [microsoft/vscode-vsce#544]
Question: How do I include OS specific binaries in an VSCode extension?

I have created an own extension, which need to call OS specific binary files with parameters. 
What is the best practice to do this in an vscode extension?

Do I have to include binaries for all supported OS or is there another option?

**Comment by joaomoreno** [comment]
> Do I have to include binaries for all supported OS or is there another option?

Yeah this is the current suggestion. We're working on having platform specific extensions, but it is still in the horizon, not yet on a plan.

**Comment by szw0407** [comment]
May it be possible to download the corresponding binary file when the extension launches the first time, and check whether the existing binary is up to date at times? Although network connection is required, I suppose it would work in most cases.

Anyway, it has been about 3 years since the issue was closed. Has anything changed yet about the *platform specific extension* plan? Thanks.
