### ISSUE TITLE
nested .vscodeignore?

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode-vsce#67]
For .gitignore, I can have a hierarchy rather that always adding to the root .gitignore. Through experimentation I have found that .vscodeignore does not behave this way. It would be awesome if it did.

**Comment by joaomoreno** [comment]
This iteration we focus on issue grooming. This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
