### ISSUE TITLE
Can't login without GUI(inside wsl)

### ISSUE THREAD

**Issue by fakusb** [microsoft/vscode-vsce#678]
It seems that since a few versions, `vsce` tries to open something using `dbus-launch` when it tries to login:

```
% vsce login my-publisher-name
 ERROR  Error spawning command line “dbus-launch --autolaunch=abfabfabf7639854378 --binary-syntax --close-stderr”: Child process exited with code 1
```

So it is not possible anymore to publish from a machine that has no GUI (like a WSL).

I'm using vsce 2.5.3,but the same problem is in vsce 2.6.0.

**Comment by joaomoreno** [comment]
> In order to save credentials safely, this project uses [keytar](https://www.npmjs.com/package/keytar) which uses `libsecret`, which you may need to install before publishing extensions. Setting the `VSCE_STORE=file` environment variable will revert back to the file credential store. Using the `VSCE_PAT` environment variable will also avoid using keytar.


https://github.com/microsoft/vscode-vsce#linux

**Comment by hamirmahal** [comment]
In Ubuntu-20.04 in WSL2, doing `VSCE_STORE=file vsce publish`, after running `sudo apt-get install libsecret-1-dev`, helped me get past the `ERROR Cannot autolaunch D-Bus without X11 $DISPLAY` message I was seeing earlier. I'm not sure if the `sudo apt-get install libsecret-1-dev` step was necessary.

Thank you for your help! I'm leaving this here in case it helps with search engine optimization, because when I searched 'vsce   ERROR Cannot autolaunch D-Bus without X11 $DISPLAY' before, no relevant search results appeared for me.

**Comment by hamirmahal** [comment]
In Ubuntu-20.04 in WSL2, running `VSCE_STORE=file vsce publish` helped me get past the `ERROR Cannot autolaunch D-Bus without X11 $DISPLAY` message I was seeing earlier.

Thank you for your help! I'm leaving this here in case it helps with search engine optimization, because when I searched 'vsce   ERROR Cannot autolaunch D-Bus without X11 $DISPLAY' before, no relevant search results appeared for me.
