### ISSUE TITLE
Publish throws "Bad Request(400) - Specified part does not exist in the package."

### ISSUE THREAD

**Issue by a7medkamel** [Microsoft/vscode-vsce#74]
Can't publish my package
src: https://github.com/a7medkamel/taskmill-editor-code

vsce publish output:

Publishing a7medkamel.taskmill@0.0.1...
Error: Failed Request: Bad Request(400) - Specified part does not exist in the package.

**Comment by waderyan** [comment]
Not sure if this is it, but try adding license field to your package.json

**Comment by waderyan** [comment]
That wasn't it. I was able to reproduce the error with an extension I am working on. I added the license but am having no luck.

**Comment by SrTobi** [comment]
I was able to publish your extension by accidentally using version `vsce@1.0.0`. So I investigated a little bit more and found out that it works with `vsce@1.0.x` and `vsce@1.1.x` and does not work since `vsce@1.2.0`. So it is definitely a vsce problem. By the way: I unpublished your extension afterwards :smile: 

![taskmill](https://cloud.githubusercontent.com/assets/4148534/13426495/045f68a0-dfae-11e5-990a-2645967eaf13.PNG)

**Comment by joaomoreno** [comment]
Hi @a7medkamel, I just publish a version that fixes your problem: `1.2.3`. Can you update to that? `npm install -g vsce`. Thanks.

**Comment by a7medkamel** [comment]
Thanks / works!

**Comment by JasonYan2015** [comment]
hello there
I also get  ERROR  Specified part does not exist in the package
with v1.74.0
