### ISSUE TITLE
Multiline sections in README.md are not rendered correctly in the marketplace

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/vscode-vsce#76]
Repoduce:
1. Update vsce, npm, yo, generator-code
2. Create new TypeScript Extension
3. Fill the readme.md with the following text:

```
# README
Multiline section
Multiline section
Multiline section
Multiline section

Singleline section 

Singleline section

Singleline section

Multiline section
Multiline section
Multiline section
Multiline section

Singleline section

Singleline section
```
1. Publish

Here is how it should be rendered according to markdown:
![source](https://cloud.githubusercontent.com/assets/4148534/13426012/1f3eb714-dfab-11e5-9acf-b3b7fa7aa1df.PNG)

Here is how it is actually rendered:
![marketplace](https://cloud.githubusercontent.com/assets/4148534/13426042/43727b7a-dfab-11e5-94dd-75dcfbfc5dde.PNG)

**Comment by stkb** [comment]
I came across the same issue, though didn't know where to report it, so did it in the uservoice: https://visualstudio.uservoice.com/forums/331878-visual-studio-marketplace/suggestions/12805320-markdown-rendering-of-readme-md-for-vscode-extensi

**Comment by pradeepna** [comment]
Hi SrTobi, Stkb - Thanks for reporting the issue. We have logged a defect to fix this. We are figuring out a way to let you track the status of the defect that we have logged in our internal system. Sorry for the delay and thanks for your patience. 

Regards,
Pradeep

**Comment by stkb** [comment]
@pradeepna thanks!

**Comment by pradeepna** [comment]
Hi - I spent some time looking into this today. The Marketplace expects the publisher to use the Git Flavored Markdown to document content details:

https://www.visualstudio.com/en-us/integrate/extensions/develop/manifest

![image](https://cloud.githubusercontent.com/assets/17713256/13621345/ce9436d0-e54b-11e5-9ebe-02f8c86f38d0.png)

We do not want to change this default behavior now. I am thinking of exposing another key in content to indicate that the content is not "Git flavored markdown" so that publishers that set this key can use the standard md syntax for line breaks.

Regards,
Pradeep

**Comment by SrTobi** [comment]
But doesn't the Github flavored markdown  handle the line breaks in the same way, the normal markdown does? I mean on github.com the multiple lines are rendered as expected. Compare for example [this Readme ](https://github.com/SrTobi/code-bing/blob/master/README.md) with it's [raw version](https://raw.githubusercontent.com/SrTobi/code-bing/master/README.md).

**Comment by stkb** [comment]
@pradeepna @SrTobi Indeed, this issue is precisely that the way the marketplace renders the markdown is contrary to "GitHub flavoured markdown", (and to the [common markdown spec](http://spec.commonmark.org/0.24/#paragraphs))

To illustrate more plainly, using SrTobi's example:
![43727b7a-dfab-11e5-94dd-75dcfbfc5dde](https://cloud.githubusercontent.com/assets/6125444/13627462/d3254b4c-e5ca-11e5-8230-213f44c13b3a.png)
![readme-github](https://cloud.githubusercontent.com/assets/6125444/13627467/d7fc976a-e5ca-11e5-8de3-678b77d288ad.png)

**Comment by pradeepna** [comment]
@SrTobi, @stkb - GitHub does not use GFM (Git flavored markdown) for Readme.md. It uses it when you post some markdown in comments (like the one where I am typing). The documentation on Github is not clear about that though. I have sent a request to GitHub to know the definitive behavior of line break in GFM. I will post their response here. 

There are some threads on this. Obviously we cannot treat them as authoritative. Will wait for response from GitHub.

http://stackoverflow.com/questions/18019957/where-is-github-flavored-markdown-gfm-actually-used-in-github

http://stackoverflow.com/questions/24575680/new-lines-inside-paragraph-in-readme-md

But I agree with you on the confusion here. If we were to start over again, we would have chosen the standard markdown. However, at this time, I feel the best recourse is to have a property in the config that controls how the markdown files are interpreted.

Regards,
Pradeep

**Comment by stkb** [comment]
@pradeepna Ah, now I see; thanks for explaining!

If the readme could render exactly as it does on GitHub then that would be very welcome, and if it has to be done with an option, then that's ok; but I think it will remain a point of confusion for some.

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

**Comment by pkuma-msft** [comment]
Hi @joaomoreno  - any action here for us? GFM behavior can be controlled using a property in the manifest: **Id='Microsoft.VisualStudio.Services.GitHubFlavoredMarkdown' and Value="true" or "false"**. 

See https://github.com/Microsoft/vscode-vsce/issues/117

**Comment by joaomoreno** [comment]
Oh sweet. We just forgot to close the issue then! Thanks!
