### ISSUE TITLE
Don't fail on CI if extension with this verison already exists

### ISSUE THREAD

**Issue by rokklobster** [microsoft/vscode-vsce#775]
**The problem**: when extension is being published, `vsce` exits with code `1` and error message if version being published already exists in marketplace.

While this behavior is natural, it breaks CI flows when you just need to skip publishing step instead of breaking the pipeline at _literally no reason_. Nuget (as an example) contains `skip-duplicate` flag, same for pypi.

Changing pipeline settings to allowing failures for publishing step is not an option - this allows for misconfigured step to be present on the pipeline.

**Proposed solution**: add flag `skip-duplicate` allowing to exit with code `0` when attempting to publish already existing version.

**Comment by felipecrs** [comment]
But why would your CI run `vsce publish` against the same version multiple times?

**Comment by rokklobster** [comment]
I have a monorepo which holds an extension along with the app, and a single CI do everything - pack apps, publish them to private repo, publish extension to market, deploy envs... I don't want to use semver on extension (private reasons), and I don't think it's a really good idea to search through marketplace and parse versions to check that I can push a package - especially since most of the tools I'm familiar with (pip, nuget, npm) allows to skip publishing dupe version

**Comment by felipecrs** [comment]
Interesting, so that you simply always run `vsce publish` in your CI, no matter the condition, but it will only get actually published if none was published before.

Effectively it means that it will only publish when you change the version in package.json.

I never thought on this, usually I use semantic-release, but otherwise I would create an specific GitHub workflow that gets triggered every time I push a git tag.
