### ISSUE TITLE
Publishing universal VSIX failing after platform-specific ones have been published

### ISSUE THREAD

**Issue by sophio-japharidze-sonarsource** [microsoft/vscode-vsce#785]
Hello dear VSCE maintainers!

**Background**
We are packaging and publishing our VSCode extension using vsce. We are publishing 4 platform-specific VSIXs, and one universal VSIX. The use case is that in the platform-specific VSIXs we embed the Java runtime that is needed to run the extension, while for the universal VSIX (all other platforms) we use the user’s configured Java runtime.

**Problem**
Automatic publishing of the universal VSIX (without the `target` option) after publishing the platform-specific ones is failing with an error

`Error: ACompany.an.extension v3.10.0 already exists.`

It is worth mentioning that the manual upload of the universal VSIX to the marketplace works without any problems.

**Additional information**
This issue could be possibly related to the https://github.com/microsoft/vscode-vsce/issues/623

The script that we use for GitHub actions can be found [here](https://github.com/SonarSource/sonarlint-vscode/blob/master/.github/actions/vsce-publish/main.js).

Could you please let us know if this is expected behavior? How could we successfully automate publishing 4 platform-specific VSIXs and finally a universal one for the same version?

Happy to provide you with any additional information,
Thank you in advance,
Sophio

**Comment by isidorn** [comment]
@sophio-japharidze-sonarsource thanks for reaching out. Can you share your universal .vsix maybe?
This is not expected behaviour and ideally we can fix this.

@joaomoreno seems like this error is coming from vsce https://github.dev/microsoft/vscode-vsce/blob/df59e0f6d35da9f0e2f6138d82534667a96527a3/src/publish.ts#L179
And not from the Marketplace.

**Comment by sophio-japharidze-sonarsource** [comment]
Hello @isidorn, thanks a lot for your reply.

I am unable to attach the VSIX here but you should be able to find the artifacts in the assets of our [releases](https://github.com/SonarSource/sonarlint-vscode/releases). The first VSIXes, without the platform specified in the title, are the universal ones.

Happy to provide any other details,
Best,
Sophio

**Comment by felipecrs** [comment]
Hopefully someday this will get addressed:

- https://github.com/microsoft/vsmarketplace/issues/219

And therefore this can be handled more gracefully.

**Comment by felipecrs** [comment]
@isidorn, this does not make sense. According to:

- https://github.com/microsoft/vsmarketplace/issues/219#issuecomment-1137119613

VS Marketplace supports publishing both platform-specific and universal vsix for a single version.

**Comment by isidorn** [comment]
@felipecrs yes, and I believe that's a bug on the Marketplace. Thus I pinged @saikanth007

**Comment by SaiKanth007** [comment]
@isidorn 



> So once an extension version has a platform specific asset, you can no longer publish a non-platform specific asset for that same version. This is a design decision we made and we do not plan to change it. So for your extension it would be best if you publish for each platform through vsce specifically. I hope that works for your use case.
> 

I am afraid this is not true, Marketplace supports publishing platform specific VSIX's and universal in any order. There are good number of extensions in marketplace which have both platform and non-platform VSIX's with non-platform VSIX's being published after platform VSIX (ex: https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode).

I guess we should remove this restriction if we have it on vsce.

**Comment by jblievremont** [comment]
@isidorn

> This is a design decision we made and we do not plan to change it.

What could make you reconsider this?

With this design, if an extension developer wants to support all platforms and enhance the user experience only for a few platforms, they have to build identical packages for all remaining platforms.

This looks to me like a waste of computing resources (with respect to building a single universal VSIX). Furthermore, it makes the build and publishing process that much more error prone, since each build + publication can fail separately for any reason (network, availability of the service). Finally, this puts the maintenance burden completely on the extension developer's side when the list of platforms supported by VSCode / vsce changes.

Ultimately, I believe the developer experience would be hugely improved by allowing extension developers to publish an additional universal package alongside with the platform specific ones.

**Comment by isidorn** [comment]
I just discussed with @joaomoreno and we agreed to investigate to remove this restriction on the vsce side.
We have to check that this does not break any of the other assumptions we are making.

So for now I will reopen this issue, and I will share more information once we have something.
Thanks for understanding.

**Comment by felipecrs** [comment]
@joaomoreno just to be completely sure about this:

It means I no longer need to publish one each vsix for every platform, but only the ones I have specific code/binary for. Previously, if I had only binary for Windows x64, I had to build and publish a vsix without any binary for every other target. Now, all I need is to build and publish a target for windows x64, and another one without any `--target`.

Is my understanding correct?

**Comment by joaomoreno** [comment]
Yes, that is correct. Once a restriction on the VS Marketplace, this is now fully supported!
