### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by mering** [microsoft/vscode-vsce#906]
Running the same build twice produces different archives as timestamps differ.

Please add an option `--reproducible` which would set the timestamp to a fixed value.

We are currently using the following workaround:
```
EXT_LOCAL_NAME=$(pwd)/my-extension.vsix
vsce package --allow-missing-repository -o ${EXT_LOCAL_NAME}

# Create reproducible archive by setting deterministic timestamp
TMPDIR=$(mktemp -d)
unzip -q ${EXT_LOCAL_NAME} -d ${TMPDIR}
rm -f ${EXT_LOCAL_NAME}
cd ${TMPDIR} && find -exec touch -d 1970-01-01T00:00:00Z "{}" \; && zip -q -r -oX ${EXT_LOCAL_NAME} *
rm -rf ${TMPDIR}
```

**Comment by joaomoreno** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
